title: Matt's Micro Madnress
author: Matthew Nobile
email: matthewnobile2495@gmail.com
description: A student's personal website.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
