title: Matthew Micro Madness
author: Matthew Nobile  
email: Matthewnobile2495@gmail.com
description: A students simple website
theme: minima

# social links
github_username:  mnobile2495

show_excerpts: true # set to false to remove excerpts on the homepage
