title: Matthew's Personal Landing Page
author: Matthew Nobile  
email: Matthewnobile2495@gmail.com
description: Computer Scientist. Software Engineer. 
theme: minima

# social links
github_username:  mnobile2495

show_excerpts: true # set to false to remove excerpts on the homepage
