title: Matthew Micro Madness
author: Matthew Nobile  
email: Matthewnobile2495@gmail.com
description: A students simple website
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
